#!/bin/sh

APP_VERSION='latest'
APP_GIT_REPO_NAME="db-manager-server-symfony"
APP_DOWNLOAD_LINK="https://app.dbvisor.pro/download/${APP_GIT_REPO_NAME}-${APP_VERSION}.zip"

APP_NAME="dbvisor-agent"
APP_DIR=".dbvisor-agent"
APP_FULL_PATH="$HOME/$APP_DIR/"

_output() {
    style_start=""
    style_end=""
    if [ "${2:-}" != "" ]; then
        case $2 in
            "success")
                style_start="\033[0;32m"
                style_end="\033[0m"
                ;;
            "error")
                style_start="\033[31;31m"
                style_end="\033[0m"
                ;;
            "info"|"warning")
                style_start="\033[33m"
                style_end="\033[39m"
                ;;
            "heading")
                style_start="\033[1;33m"
                style_end="\033[22;39m"
                ;;
            "comment")
                style_start="\033[2m"
                style_end="\033[22;39m"
                ;;
        esac
    fi
    printf "${style_start}${1}${style_end}\n"
}

_intro() {
    _output "+--------------------------------------------------+" "heading"
    _output "|                                                  |" "heading"
    _output "|             DB Visor Agent Installer             |" "heading"
    _output "|                                                  |" "heading"
    _output "+--------------------------------------------------+" "heading"
}

_intro

mkdir -p "$APP_FULL_PATH"

_output "\n Downloading source server code " "heading"
curl -skL "${APP_DOWNLOAD_LINK}" -o /tmp/"${APP_NAME}"-tmp.zip

if [ ! -f "/tmp/${APP_NAME}-tmp.zip" ] || [ $(wc -c < "/tmp/${APP_NAME}-tmp.zip") -lt 200 ]; then
    _output "\nERROR: Downloading filed. Please check access to source: ${APP_DOWNLOAD_LINK}" "error"
    exit;
fi

unzip -qq -o /tmp/"${APP_NAME}"-tmp.zip -d "${APP_FULL_PATH}"

exec "${APP_FULL_PATH}dbvisor-agent" setup
